version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '127.0.0.1:27017:27017'
  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - '2181'
    ports:
      - '127.0.0.1:2181:2181'
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '127.0.0.1:9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: |
        example.device.v1.pb:1:1:compact,\
        example.organization.v1.pb:1:1:compact

  